name: ml2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.9
  - appnope
  - asttokens
  - bzip2
  - ca-certificates
  - comm
  - debugpy
  - decorator
  - exceptiongroup
  - executing
  - importlib-metadata
  - ipykernel
  - ipython
  - jedi
  - jupyter_client
  - jupyter_core
  - krb5
  - libcxx
  - libexpat
  - libffi
  - libmpdec
  - libsodium
  - matplotlib-inline
  - nest-asyncio
  - openssl
  - packaging
  - parso
  - pexpect
  - pickleshare
  - pip
  - platformdirs
  - prompt-toolkit
  - psutil
  - ptyprocess
  - pure_eval
  - pygments
  - python
  - python-dateutil
  - pyzmq
  - scikit-learn
  - setuptools
  - six
  - sqlite
  - stack_data
  - tk
  - tornado
  - traitlets
  - typing_extensions
  - tzdata
  - wcwidth
  - wheel
  - xz
  - zeromq
  - zipp
  - zlib
  - pip:
    - contourpy
    - cycler
    - fonttools
    - ipywidgets
    - joblib
    - jupyterlab-widgets
    - kiwisolver
    - matplotlib==3.9.2
    - numpy==2.1.2
    - pillow
    - pyparsing
    - scipy
    - threadpoolctl
    - widgetsnbextension